---
# Join the worker node to the Kubernetes cluster
- name: Join the worker node to cluster
  shell: "{{ hostvars['master']['join_command'] }}"
  register: worker_join
  changed_when: worker_join.rc == 0
  failed_when: 
    - worker_join.rc != 0 
    - "'already initialized as a master node' not in worker_join.stderr"
    - "'already exists' not in worker_join.stderr"
  args:
    creates: /etc/kubernetes/kubelet.conf