---
# Download the GPG key for Docker
- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: ./docker.key
    mode: '0600'

- name: Import Docker GPG key
  shell: |
    gpg --no-default-keyring --keyring ./docker.gpg --import ./docker.key
    gpg --no-default-keyring --keyring ./docker.gpg --export > ./docker-archive-keyring.gpg
    mv ./docker-archive-keyring.gpg /etc/apt/trusted.gpg.d/
  args:
    creates: /etc/apt/trusted.gpg.d/docker-archive-keyring.gpg

# Add Docker repository
- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

# Install Docker
- name: Install Docker
  apt:
    name: docker-ce
    state: present
    update_cache: yes

# Install cri-dockerd
- name: Get latest cri-dockerd version
  shell: curl -s https://api.github.com/repos/Mirantis/cri-dockerd/releases/latest | grep tag_name | cut -d '"' -f 4 | sed 's/v//g'
  register: cri_dockerd_version
  changed_when: false

- name: Download cri-dockerd
  get_url:
    url: "https://github.com/Mirantis/cri-dockerd/releases/download/v{{ cri_dockerd_version.stdout }}/cri-dockerd-{{ cri_dockerd_version.stdout }}.amd64.tgz"
    dest: /tmp/cri-dockerd.tgz
    mode: '0644'

- name: Extract cri-dockerd
  unarchive:
    src: /tmp/cri-dockerd.tgz
    dest: /tmp
    remote_src: yes

- name: Move cri-dockerd binary to /usr/local/bin
  copy:
    src: /tmp/cri-dockerd/cri-dockerd
    dest: /usr/local/bin/
    mode: '0755'
    remote_src: yes

# Configure cri-dockerd services
- name: Download cri-docker service files
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  with_items:
    - { url: 'https://raw.githubusercontent.com/Mirantis/cri-dockerd/master/packaging/systemd/cri-docker.service', dest: '/etc/systemd/system/cri-docker.service' }
    - { url: 'https://raw.githubusercontent.com/Mirantis/cri-dockerd/master/packaging/systemd/cri-docker.socket', dest: '/etc/systemd/system/cri-docker.socket' }

- name: Update cri-docker.service file
  replace:
    path: /etc/systemd/system/cri-docker.service
    regexp: '/usr/bin/cri-dockerd'
    replace: '/usr/local/bin/cri-dockerd'

- name: Reload systemd, enable and start cri-docker services
  systemd:
    name: "{{ item }}"
    daemon_reload: yes
    enabled: yes
    state: started
  with_items:
    - cri-docker.socket
    - cri-docker.service